### ISSUE TITLE
Support for dbt 1.8

### ISSUE THREAD

**Issue by sdebruyn** [z3z1ma/dbt-osmosis#139]
The package fails with dbt 1.8 with the error `ModuleNotFoundError: No module named 'dbt.clients.system'`
in dbt 1.8 a lot of modules and packages have been moved around so this plugin probably needs an update.

**Comment by z3z1ma** [comment]
Fixed by #151 , will cut new release on pypi today.

**Comment by Datayama38** [comment]
This package still fail with dbt-core 1.8. Fix in PR #151 is not in last release (0.12.10) on pypi
Can you make a new release please ?
